### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
image_min_pixels: 784
image_max_pixels: 1003520
trust_remote_code: true
flash_attn: fa2

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
gradient_checkpointing: true
gradient_checkpointing_kwargs: {"use_reentrant": false}

### dataset (overridden via CLI)
dataset: placeholder
eval_dataset: placeholder
template: qwen2_vl
cutoff_len: 20480
media_dir: /scratch/gpfs/ZHUANGL/sk7524/LLaMA-Factory-AutoReviewer/data/images
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### eval
do_eval: false
eval_steps: 200

### output (overridden via CLI)
output_dir: placeholder
logging_steps: 10
save_steps: 99999
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8    # 1*2*8 = 16 effective batch
learning_rate: 2.0e-6
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0
bf16: true
ddp_timeout: 180000000
