### model
model_name_or_path: Qwen/Qwen2.5-3B-Instruct
image_max_pixels: 250880
video_max_pixels: 16384
trust_remote_code: true
flash_attn: fa2

### method
stage: sft
do_train: true
finetuning_type: full

### dataset
dataset: iclr_2020_2025_80_20_split5_balanced_deepreview_clean_binary_no_reviews_v3_train
template: qwen
cutoff_len: 20480
max_samples: 20000 # 20000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen2.5-3b/final_layer/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-4           # Note: Partial training often requires a higher LR than full tuning
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
gradient_checkpointing: true      
gradient_checkpointing_kwargs: {"use_reentrant": false}

### evaluation
do_eval: true
eval_dataset: iclr_2020_2025_80_20_split5_balanced_deepreview_clean_binary_no_reviews_v3_test
eval_strategy: steps
eval_steps: 500 # 500
per_device_eval_batch_size: 1