### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
trust_remote_code: true
flash_attn: fa2

### method
stage: sft
do_train: true
finetuning_type: full
gradient_checkpointing: true
gradient_checkpointing_kwargs: {"use_reentrant": false}

### dataset
dataset: iclr_text_binary_20480_reviews_train
eval_dataset: iclr_text_binary_20480_reviews_test
template: qwen
cutoff_len: 20480
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### eval
do_eval: false
eval_steps: 200

### output
output_dir: saves/qwen2.5-7b/full/iclr_sft_reviews_v2
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 2.0e-6
num_train_epochs: 1.0
lr_scheduler_type: constant_with_warmup
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
