### model
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
trust_remote_code: true
flash_attn: fa2
enable_liger_kernel: True

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: iclr_2020_2025_85_5_10_split6_original_vision_binary_noreviews_v6_train
media_dir: .
template: qwen2_vl
cutoff_len: 16384 # crashes with 20480
max_samples: 20000
overwrite_cache: false
preprocessing_num_workers: 16
dataloader_num_workers: 4

# Use pre-tokenized dataset (run sbatch/cache_tokenized_dataset.sbatch first)
tokenized_path: cache/tokenized_qwen2_5_3bvl_sft

### output
output_dir: saves/qwen2.5vl-3b/full/sft_ds3
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
image_max_pixels: 250880
image_min_pixels: 196
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
gradient_checkpointing: true
gradient_checkpointing_kwargs: {"use_reentrant": false}

### evaluation
do_eval: true
eval_dataset: iclr_2020_2025_85_5_10_split6_original_vision_binary_noreviews_v6_validation
eval_strategy: steps
eval_steps: 500
per_device_eval_batch_size: 1
