### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
image_min_pixels: 2352 # 3*28**2
image_max_pixels: 2104256 # 2684*(28**2)
video_max_pixels: 2104256 # 2684*(28**2)
trust_remote_code: true
flash_attn: fa2

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false

### dataset
dataset: iclr_clean+images_binary_no_reviews_v3
template: qwen2_vl
cutoff_len: 20480
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen2.5-vl-7b/full/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0
bf16: true
ddp_timeout: 180000000
