### Model
model_name_or_path: /scratch/gpfs/ZHUANGL/jl0796/shared/saves/best_2025_2026_text/checkpoint-1322
trust_remote_code: true
flash_attn: disabled
bf16: true

### Method
stage: sft
do_predict: true
do_train: false
finetuning_type: full
per_device_eval_batch_size: 1

### Dataset
dataset_dir: /scratch/gpfs/ZHUANGL/jl0796/shared/data
eval_dataset: iclr_balanced_50_test
template: qwen
cutoff_len: 20000
max_samples: 50

### Output
output_dir: saves/best_2025_2026_text_balanced
overwrite_output_dir: true
logging_steps: 1

### Eval
predict_with_generate: true
remove_unused_columns: false

### Text Attention Visualization Hook
visualize_attention_text: true
attention_viz_text_output_dir: outputs/best_2025_2026_text_balanced
attention_viz_max_new_tokens: 128
