### Model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
trust_remote_code: true

### Method
stage: cls
finetuning_type: full
gradient_checkpointing: true

### Dataset
dataset: iclr_2020_2025_85_5_10_split7_balanced_vision_binary_noreviews_v7_train
template: qwen2_vl
cutoff_len: 8192
max_samples: 1000

### Output
output_dir: saves/test_cls_vision
logging_steps: 10
save_strategy: no
plot_loss: true

### Train
bf16: true
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 1
do_train: true
